root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "tmp\\main.exe"
  cmd = "go build -o ./tmp/main.exe ."
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "public", "bootstrap", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false # Para reconstruir siempre
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "svelte", "js", "css"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  rerun = false # Volver a ejecutar en cada cambio
  rerun_delay = 1000
  pre_cmd = ["yarn build"]
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 3000
  enabled = true
  proxy_port = 3001

[screen]
  clear_on_rebuild = true
  keep_scroll = true
